const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const src = fs.readFileSync(require('node:path').join(__dirname,'../skills/video-cut/studio/js/inspector.js'),'utf8').replace(/\r\n/g,'\n');
const fn = src.match(/  function colorSlider\([\s\S]*?\n  }\n/)[0];
const el = () => ({children:[],dataset:{},_value:'',get value(){return this._value;},set value(v){this._value=String(v);},setAttribute(){},appendChild(n){this.children.push(n);}});
let snapshots = 0, applied = [];
const sandbox={el,field:(_,n)=>n,clamp:(v,a,b)=>Math.min(b,Math.max(a,v)),st:{push:()=>snapshots++}};
vm.createContext(sandbox); vm.runInContext(fn,sandbox);
const [range, number] = sandbox.colorSlider('brightness','brillo',0,-0.4,0.4,0.01,v=>applied.push(v)).children;
number.value='0.13'; number.oninput();
assert.equal(range.value,'0.13'); assert.equal(snapshots,1);
number.value='0.23'; number.oninput(); assert.equal(snapshots,1);
number.onblur(); assert.equal(number.value,'0.23');
number.value=''; number.oninput(); number.onblur(); assert.equal(number.value,'0.23');
number.value='NaN'; number.onchange(); assert.equal(number.value,'0.23');
number.value='99'; number.oninput(); number.onblur(); assert.equal(number.value,'0.40'); assert.equal(snapshots,2);
range.value='-0.2'; range.oninput(); range.value='-0.1'; range.oninput(); range.onchange();
assert.equal(number.value,'-0.10'); assert.equal(snapshots,3);
const [sr,sn] = sandbox.colorSlider('saturation','saturación',1,0,2.5,0.01,v=>applied.push(v)).children;
sn.value='0'; sn.oninput(); assert.equal(sr.value,'0'); assert.equal(applied.at(-1),0);
console.log('PASS: numeric/range sync, neutral/zero, limits, invalid input, one undo per gesture.');
